services:
  nginx:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/modsecurity:/etc/nginx/modsecurity
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - varnish
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  varnish:
    image: varnish:7.3
    ports:
      - "8080:80"
      - "6082:6082"
    volumes:
      - ./varnish:/etc/varnish
    environment:
      - VARNISH_SIZE=2G
    command: >
      -p default_ttl=3600
      -p default_grace=3600
      -p varnishd_stats_enabled=true
      -T 0.0.0.0:6082
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "varnishstat", "-1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  consul:
    image: hashicorp/consul:1.16
    ports:
      - "8501:8500"  # Changed to avoid port conflict
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    command: >
      agent -server -bootstrap-expect=1 -ui
      -client=0.0.0.0
      -config-dir=/consul/config
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    command:
      - -nginx.scrape-uri=http://nginx:8080/stub_status
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9113/metrics"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxy-net

  varnish-metrics:
    image: varnish:7.3
    volumes:
      - /var/lib/varnish:/var/lib/varnish
    entrypoint: ["varnishstat"]
    command: ["-1", "-j"]
    depends_on:
      varnish:
        condition: service_healthy
    networks:
      - proxy-net

  goaccess:
    image: allinurl/goaccess:1.7
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./goaccess:/etc/goaccess
    command: >
      touch /var/log/nginx/access.log &&
      goaccess /var/log/nginx/access.log
      --config-file=/etc/goaccess/goaccess.conf
      --real-time-html
      --ws-url=ws://localhost:7890
      --port=7890
      -o /var/log/nginx/report.html
    ports:
      - "7890:7890"
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge

volumes:
  grafana-storage:
  prometheus_data: